import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser, WebhooksDeployPusherType, WebhooksRef 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DeleteEvent {
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  pusher_type: WebhooksDeployPusherType;
  ref: WebhooksRef;
  /**
   * The type of Git ref object deleted in the repository.
   */
  ref_type: 'tag' | 'branch';
  repository: RepositoryWebhooks;
  sender: SimpleUser;
}
