import type {
  EnterpriseWebhooks, Installation, OrganizationSimple, RepositoryWebhooks, SimpleUser, WebhooksRepositoriesAdded, WebhooksRepositorySelection, WebhooksUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InstallationRepositoriesAddedEvent {
  action: 'added';
  enterprise?: EnterpriseWebhooks;
  installation: Installation;
  organization?: OrganizationSimple;
  repositories_added: WebhooksRepositoriesAdded;
  /**
   * An array of repository objects, which were removed from the installation.
   */
  repositories_removed: {
    full_name?: string,
    /**
     * Unique identifier of the repository
     */
    id?: number,
    /**
     * The name of the repository.
     */
    name?: string,
    node_id?: string,
    /**
     * Whether the repository is private or public.
     */
    private?: boolean
  }[];
  repository?: RepositoryWebhooks;
  repository_selection: WebhooksRepositorySelection;
  requester: WebhooksUser;
  sender: SimpleUser;
}
