import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, RubyGemsMetadata, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RegistryPackagePublishedEvent {
  action: 'published';
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  registry_package: {
    created_at: string | null,
    description: string | null,
    ecosystem: string,
    html_url: string,
    id: number,
    name: string,
    namespace: string,
    owner: {
      avatar_url: string,
      events_url: string,
      followers_url: string,
      following_url: string,
      gists_url: string,
      gravatar_id: string,
      html_url: string,
      id: number,
      login: string,
      node_id: string,
      organizations_url: string,
      received_events_url: string,
      repos_url: string,
      site_admin: boolean,
      starred_url: string,
      subscriptions_url: string,
      type: string,
      url: string,
      user_view_type?: string
    },
    package_type: string,
    package_version: {
      author?: {
        avatar_url: string,
        events_url: string,
        followers_url: string,
        following_url: string,
        gists_url: string,
        gravatar_id: string,
        html_url: string,
        id: number,
        login: string,
        node_id: string,
        organizations_url: string,
        received_events_url: string,
        repos_url: string,
        site_admin: boolean,
        starred_url: string,
        subscriptions_url: string,
        type: string,
        url: string,
        user_view_type?: string
      },
      body?: string | {},
      body_html?: string,
      container_metadata?: {
        labels?: {} | null,
        manifest?: {} | null,
        tag?: {
          digest?: string,
          name?: string
        }
      },
      created_at?: string,
      description: string,
      docker_metadata?: {
        tags?: string[]
      }[],
      draft?: boolean,
      html_url: string,
      id: number,
      installation_command: string,
      manifest?: string,
      metadata: {
        [k: string]: unknown | undefined
      }[],
      name: string,
      npm_metadata?: {
        name?: string,
        version?: string,
        npm_user?: string,
        author?: string | {} | null,
        bugs?: string | {} | null,
        dependencies?: {},
        dev_dependencies?: {},
        peer_dependencies?: {},
        optional_dependencies?: {},
        description?: string,
        dist?: string | {} | null,
        git_head?: string,
        homepage?: string,
        license?: string,
        main?: string,
        repository?: string | {} | null,
        scripts?: {},
        id?: string,
        node_version?: string,
        npm_version?: string,
        has_shrinkwrap?: boolean,
        maintainers?: string[],
        contributors?: string[],
        engines?: {},
        keywords?: string[],
        files?: string[],
        bin?: {},
        man?: {},
        directories?: string | {} | null,
        os?: string[],
        cpu?: string[],
        readme?: string,
        installation_command?: string,
        release_id?: number,
        commit_oid?: string,
        published_via_actions?: boolean,
        deleted_by_id?: number
      } | null,
      nuget_metadata?:
        | {
          id?: string | {} | number | null,
          name?: string,
          value?:
              | boolean
              | string
              | number
              | {
                url?: string,
                branch?: string,
                commit?: string,
                type?: string
              }
        }[]
        | null,
      package_files: {
        content_type: string,
        created_at: string,
        download_url: string,
        id: number,
        md5: string | null,
        name: string,
        sha1: string | null,
        sha256: string | null,
        size: number,
        state: string | null,
        updated_at: string
      }[],
      package_url: string,
      prerelease?: boolean,
      release?: {
        author?: {
          avatar_url?: string,
          events_url?: string,
          followers_url?: string,
          following_url?: string,
          gists_url?: string,
          gravatar_id?: string,
          html_url?: string,
          id?: number,
          login?: string,
          node_id?: string,
          organizations_url?: string,
          received_events_url?: string,
          repos_url?: string,
          site_admin?: boolean,
          starred_url?: string,
          subscriptions_url?: string,
          type?: string,
          url?: string,
          user_view_type?: string
        },
        created_at?: string,
        draft?: boolean,
        html_url?: string,
        id?: number,
        name?: string | null,
        prerelease?: boolean,
        published_at?: string,
        tag_name?: string,
        target_commitish?: string,
        url?: string
      },
      rubygems_metadata?: RubyGemsMetadata[],
      summary: string,
      tag_name?: string,
      target_commitish?: string,
      target_oid?: string,
      updated_at?: string,
      version: string
    } | null,
    registry: {
      about_url?: string,
      name?: string,
      type?: string,
      url?: string,
      vendor?: string
    } | null,
    updated_at: string | null
  };
  repository?: RepositoryWebhooks;
  sender: SimpleUser;
}
