import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, RubyGemsMetadata, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RegistryPackageUpdatedEvent {
  action: 'updated';
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  registry_package: {
    created_at: string,
    description: null,
    ecosystem: string,
    html_url: string,
    id: number,
    name: string,
    namespace: string,
    owner: {
      avatar_url: string,
      events_url: string,
      followers_url: string,
      following_url: string,
      gists_url: string,
      gravatar_id: string,
      html_url: string,
      id: number,
      login: string,
      node_id: string,
      organizations_url: string,
      received_events_url: string,
      repos_url: string,
      site_admin: boolean,
      starred_url: string,
      subscriptions_url: string,
      type: string,
      url: string,
      user_view_type?: string
    },
    package_type: string,
    package_version: {
      author: {
        avatar_url: string,
        events_url: string,
        followers_url: string,
        following_url: string,
        gists_url: string,
        gravatar_id: string,
        html_url: string,
        id: number,
        login: string,
        node_id: string,
        organizations_url: string,
        received_events_url: string,
        repos_url: string,
        site_admin: boolean,
        starred_url: string,
        subscriptions_url: string,
        type: string,
        url: string,
        user_view_type?: string
      },
      body: string,
      body_html: string,
      created_at: string,
      description: string,
      docker_metadata?: ({
        tags?: string[]
      } | null)[],
      draft?: boolean,
      html_url: string,
      id: number,
      installation_command: string,
      manifest?: string,
      metadata: {
        [k: string]: unknown | undefined
      }[],
      name: string,
      package_files: {
        content_type?: string,
        created_at?: string,
        download_url?: string,
        id?: number,
        md5?: string | null,
        name?: string,
        sha1?: string | null,
        sha256?: string,
        size?: number,
        state?: string,
        updated_at?: string
      }[],
      package_url: string,
      prerelease?: boolean,
      release?: {
        author: {
          avatar_url: string,
          events_url: string,
          followers_url: string,
          following_url: string,
          gists_url: string,
          gravatar_id: string,
          html_url: string,
          id: number,
          login: string,
          node_id: string,
          organizations_url: string,
          received_events_url: string,
          repos_url: string,
          site_admin: boolean,
          starred_url: string,
          subscriptions_url: string,
          type: string,
          url: string,
          user_view_type?: string
        },
        created_at: string,
        draft: boolean,
        html_url: string,
        id: number,
        name: string,
        prerelease: boolean,
        published_at: string,
        tag_name: string,
        target_commitish: string,
        url: string
      },
      rubygems_metadata?: RubyGemsMetadata[],
      summary: string,
      tag_name?: string,
      target_commitish: string,
      target_oid: string,
      updated_at: string,
      version: string
    },
    registry: {} | null,
    updated_at: string
  };
  repository?: RepositoryWebhooks;
  sender: SimpleUser;
}
