import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser, WebhooksLabel 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LabelEditedEvent {
  action: 'edited';
  /**
   * The changes to the label if the action was `edited`.
   */
  changes?: {
    color?: {
      /**
       * The previous version of the color if the action was `edited`.
       */
      from: string
    },
    description?: {
      /**
       * The previous version of the description if the action was `edited`.
       */
      from: string
    },
    name?: {
      /**
       * The previous version of the name if the action was `edited`.
       */
      from: string
    }
  };
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  label: WebhooksLabel;
  organization?: OrganizationSimple;
  repository: RepositoryWebhooks;
  sender: SimpleUser;
}
