import type {
  DependabotAlert, EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DependabotAlertCreatedEvent {
  action: 'created';
  alert: DependabotAlert;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  enterprise?: EnterpriseWebhooks;
  repository: RepositoryWebhooks;
  sender: SimpleUser;
}
