import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryAdvisory, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RepositoryAdvisoryReportedEvent {
  action: 'reported';
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  repository: RepositoryWebhooks;
  repository_advisory: RepositoryAdvisory;
  sender?: SimpleUser;
}
