import type {
  MergeGroup, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MergeGroupChecksRequestedEvent {
  action: 'checks_requested';
  installation?: SimpleInstallation;
  merge_group: MergeGroup;
  organization?: OrganizationSimple;
  repository?: RepositoryWebhooks;
  sender?: SimpleUser;
}
