import type {
  MergeGroup, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MergeGroupDestroyedEvent {
  action: 'destroyed';
  /**
   * Explains why the merge group is being destroyed. The group could have been merged, removed from the queue (dequeued), or invalidated by an earlier queue entry being dequeued (invalidated).
   */
  reason?: 'merged' | 'invalidated' | 'dequeued';
  installation?: SimpleInstallation;
  merge_group: MergeGroup;
  organization?: OrganizationSimple;
  repository?: RepositoryWebhooks;
  sender?: SimpleUser;
}
