import type {
  CodeScanningAlertDismissedComment, EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CodeScanningAlertReopenedEvent {
  action: 'reopened';
  alert: {
    /**
     * The time that the alert was created in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ.`
     */
    created_at: string,
    dismissed_at: string | null,
    dismissed_by: {} | null,
    dismissed_comment?: CodeScanningAlertDismissedComment,
    dismissed_reason: string | null,
    /**
     * The time that the alert was fixed in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
     */
    fixed_at?: null,
    /**
     * The GitHub URL of the alert resource.
     */
    html_url: string,
    most_recent_instance?: {
      /**
       * Identifies the configuration under which the analysis was executed. For example, in GitHub Actions this includes the workflow filename and job name.
       */
      analysis_key: string,
      /**
       * Identifies the configuration under which the analysis was executed.
       */
      category?: string,
      classifications?: string[],
      commit_sha?: string,
      /**
       * Identifies the variable values associated with the environment in which the analysis that generated this alert instance was performed, such as the language that was analyzed.
       */
      environment: string,
      location?: {
        end_column?: number,
        end_line?: number,
        path?: string,
        start_column?: number,
        start_line?: number
      },
      message?: {
        text?: string
      },
      /**
       * The full Git reference, formatted as `refs/heads/<branch name>`.
       */
      ref: string,
      /**
       * State of a code scanning alert.
       */
      state: 'open' | 'dismissed' | 'fixed'
    } | null,
    /**
     * The code scanning alert number.
     */
    number: number,
    rule: {
      /**
       * A short description of the rule used to detect the alert.
       */
      description: string,
      full_description?: string,
      help?: string | null,
      help_uri?: string | null,
      /**
       * A unique identifier for the rule used to detect the alert.
       */
      id: string,
      name?: string,
      severity: ('none' | 'note' | 'warning' | 'error' | null) | null,
      tags?: string[] | null
    },
    state: ('open' | 'dismissed' | 'fixed' | null) | null,
    tool: {
      guid?: string | null,
      /**
       * The name of the tool used to generate the code scanning analysis alert.
       */
      name: string,
      version: string | null
    },
    url: string
  } | null;
  commit_oid: string | null;
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  ref: string | null;
  repository: RepositoryWebhooks;
  sender: SimpleUser;
}
