import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser, WebhooksDeployPusherType, WebhooksRef 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateEvent {
  description: string | null;
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  /**
   * The name of the repository's default branch (usually `main`).
   */
  master_branch: string;
  organization?: OrganizationSimple;
  pusher_type: WebhooksDeployPusherType;
  ref: WebhooksRef;
  /**
   * The type of Git ref object created in the repository.
   */
  ref_type: 'tag' | 'branch';
  repository: RepositoryWebhooks;
  sender: SimpleUser;
}
