import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CommitCommentCreatedEvent {
  /**
   * The action performed. Can be `created`.
   */
  action: 'created';
  /**
   * The [commit comment](${externalDocsUpapp/api/description/components/schemas/webhooks/issue-comment-created.yamlrl}/rest/commits/comments#get-a-commit-comment) resource.
   */
  comment: {
    /**
     * How the author is associated with the repository.
     */
    author_association:
      | 'COLLABORATOR'
      | 'CONTRIBUTOR'
      | 'FIRST_TIMER'
      | 'FIRST_TIME_CONTRIBUTOR'
      | 'MANNEQUIN'
      | 'MEMBER'
      | 'NONE'
      | 'OWNER',
    /**
     * The text of the comment.
     */
    body: string,
    /**
     * The SHA of the commit to which the comment applies.
     */
    commit_id: string,
    created_at: string,
    html_url: string,
    /**
     * The ID of the commit comment.
     */
    id: number,
    /**
     * The line of the blob to which the comment applies. The last line of the range for a multi-line comment
     */
    line: number | null,
    /**
     * The node ID of the commit comment.
     */
    node_id: string,
    /**
     * The relative path of the file to which the comment applies.
     */
    path: string | null,
    /**
     * The line index in the diff to which the comment applies.
     */
    position: number | null,
    reactions?: {
      '+1': number,
      '-1': number,
      confused: number,
      eyes: number,
      heart: number,
      hooray: number,
      laugh: number,
      rocket: number,
      total_count: number,
      url: string
    },
    updated_at: string,
    url: string,
    user: {
      avatar_url?: string,
      deleted?: boolean,
      email?: string | null,
      events_url?: string,
      followers_url?: string,
      following_url?: string,
      gists_url?: string,
      gravatar_id?: string,
      html_url?: string,
      id: number,
      login: string,
      name?: string,
      node_id?: string,
      organizations_url?: string,
      received_events_url?: string,
      repos_url?: string,
      site_admin?: boolean,
      starred_url?: string,
      subscriptions_url?: string,
      type?: 'Bot' | 'User' | 'Organization',
      url?: string,
      user_view_type?: string
    } | null
  };
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  repository: RepositoryWebhooks;
  sender: SimpleUser;
}
