import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InstallationTargetRenamedEvent {
  account: {
    archived_at?: string | null,
    avatar_url: string,
    created_at?: string,
    description?: null,
    events_url?: string,
    followers?: number,
    followers_url?: string,
    following?: number,
    following_url?: string,
    gists_url?: string,
    gravatar_id?: string,
    has_organization_projects?: boolean,
    has_repository_projects?: boolean,
    hooks_url?: string,
    html_url: string,
    id: number,
    is_verified?: boolean,
    issues_url?: string,
    login?: string,
    members_url?: string,
    name?: string,
    node_id: string,
    organizations_url?: string,
    public_gists?: number,
    public_members_url?: string,
    public_repos?: number,
    received_events_url?: string,
    repos_url?: string,
    site_admin?: boolean,
    slug?: string,
    starred_url?: string,
    subscriptions_url?: string,
    type?: string,
    updated_at?: string,
    url?: string,
    website_url?: null,
    user_view_type?: string
  };
  action: 'renamed';
  changes: {
    login?: {
      from: string
    },
    slug?: {
      from: string
    }
  };
  enterprise?: EnterpriseWebhooks;
  installation: SimpleInstallation;
  organization?: OrganizationSimple;
  repository?: RepositoryWebhooks;
  sender?: SimpleUser;
  target_type: string;
}
