import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RepositoryTransferredEvent {
  action: 'transferred';
  changes: {
    owner: {
      from: {
        organization?: {
          avatar_url: string,
          description: string | null,
          events_url: string,
          hooks_url: string,
          html_url?: string,
          id: number,
          issues_url: string,
          login: string,
          members_url: string,
          node_id: string,
          public_members_url: string,
          repos_url: string,
          url: string
        },
        user?: {
          avatar_url?: string,
          deleted?: boolean,
          email?: string | null,
          events_url?: string,
          followers_url?: string,
          following_url?: string,
          gists_url?: string,
          gravatar_id?: string,
          html_url?: string,
          id: number,
          login: string,
          name?: string,
          node_id?: string,
          organizations_url?: string,
          received_events_url?: string,
          repos_url?: string,
          site_admin?: boolean,
          starred_url?: string,
          subscriptions_url?: string,
          type?: 'Bot' | 'User' | 'Organization',
          url?: string,
          user_view_type?: string
        } | null
      }
    }
  };
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  repository: RepositoryWebhooks;
  sender: SimpleUser;
}
