import type {
  EnterpriseWebhooks, OrganizationSimple, PullRequestWebhook, RepositoryWebhooks, SimpleInstallation, SimpleUser, WebhooksNumber 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PullRequestEditedEvent {
  action: 'edited';
  /**
   * The changes to the comment if the action was `edited`.
   */
  changes: {
    base?: {
      ref: {
        from: string
      },
      sha: {
        from: string
      }
    },
    body?: {
      /**
       * The previous version of the body if the action was `edited`.
       */
      from: string
    }
  };
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  number: WebhooksNumber;
  organization?: OrganizationSimple;
  pull_request: PullRequestWebhook;
  repository: RepositoryWebhooks;
  sender?: SimpleUser;
}
