import type {
  EnterpriseWebhooks, Milestone, OrganizationSimple, RepositoryWebhooks, SimpleUser, WebhooksNumber, WebhooksPullRequest 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PullRequestMilestonedEvent {
  action: 'milestoned';
  enterprise?: EnterpriseWebhooks;
  milestone?: Milestone;
  number: WebhooksNumber;
  organization?: OrganizationSimple;
  pull_request: WebhooksPullRequest;
  repository: RepositoryWebhooks;
  sender?: SimpleUser;
}
