import type {
  Issue, OrganizationSimple, Repository, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SubIssuesParentIssueRemovedEvent {
  action: 'parent_issue_removed';
  /**
   * The ID of the parent issue.
   */
  parent_issue_id: number;
  parent_issue: Issue;
  parent_issue_repo: Repository;
  /**
   * The ID of the sub-issue.
   */
  sub_issue_id: number;
  sub_issue: Issue;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  repository?: RepositoryWebhooks;
  sender?: SimpleUser;
}
