import type {
  EnterpriseWebhooks, Installation, OrganizationSimple, RepositoryWebhooks, SimpleUser, WebhooksRepositories 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InstallationSuspendEvent {
  action: 'suspend';
  enterprise?: EnterpriseWebhooks;
  installation: Installation;
  organization?: OrganizationSimple;
  repositories?: WebhooksRepositories;
  repository?: RepositoryWebhooks;
  requester?: null;
  sender: SimpleUser;
}
