import type {
  EnterpriseWebhooks, OrganizationSimple, PersonalAccessTokenRequest, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PersonalAccessTokenRequestDeniedEvent {
  action: 'denied';
  personal_access_token_request: PersonalAccessTokenRequest;
  organization: OrganizationSimple;
  enterprise?: EnterpriseWebhooks;
  sender: SimpleUser;
  installation: SimpleInstallation;
}
