import type {
  OrganizationSimple, ProjectsV2Item, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProjectsV2ItemConvertedEvent {
  action: 'converted';
  changes: {
    content_type?: {
      from?: string | null,
      to?: string
    }
  };
  installation?: SimpleInstallation;
  organization: OrganizationSimple;
  projects_v2_item: ProjectsV2Item;
  sender: SimpleUser;
}
