import type {
  OrganizationSimple, ProjectsV2Item, ProjectsV2IterationSetting, ProjectsV2SingleSelectOption, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProjectsV2ItemEditedEvent {
  action: 'edited';
  /**
   * The changes made to the item may involve modifications in the item's fields and draft issue body.
   * It includes altered values for text, number, date, single select, and iteration fields, along with the GraphQL node ID of the changed field.
   */
  changes?:
    | {
      field_value: {
        field_node_id?: string,
        field_type?: string,
        field_name?: string,
        project_number?: number,
        from?:
            | string
            | number
            | ProjectsV2SingleSelectOption
            | ProjectsV2IterationSetting
            | null
            | {},
        to?:
            | string
            | number
            | ProjectsV2SingleSelectOption
            | ProjectsV2IterationSetting
            | null
            | {}
      }
    }
    | {
      body: {
        from?: string | null,
        to?: string | null
      }
    };
  installation?: SimpleInstallation;
  organization: OrganizationSimple;
  projects_v2_item: ProjectsV2Item;
  sender: SimpleUser;
}
