import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryRule, RepositoryRuleset, RepositoryRulesetConditionsForRefNames, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RepositoryRulesetEditedEvent {
  action: 'edited';
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  repository?: RepositoryWebhooks;
  repository_ruleset: RepositoryRuleset;
  changes?: {
    name?: {
      from?: string
    },
    enforcement?: {
      from?: string
    },
    conditions?: {
      added?: RepositoryRulesetConditionsForRefNames[],
      deleted?: RepositoryRulesetConditionsForRefNames[],
      updated?: {
        condition?: RepositoryRulesetConditionsForRefNames,
        changes?: {
          condition_type?: {
            from?: string
          },
          target?: {
            from?: string
          },
          include?: {
            from?: string[]
          },
          exclude?: {
            from?: string[]
          }
        }
      }[]
    },
    rules?: {
      added?: RepositoryRule[],
      deleted?: RepositoryRule[],
      updated?: {
        rule?: RepositoryRule,
        changes?: {
          configuration?: {
            from?: string
          },
          rule_type?: {
            from?: string
          },
          pattern?: {
            from?: string
          }
        }
      }[]
    }
  };
  sender: SimpleUser;
}
