import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GollumEvent {
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  /**
   * The pages that were updated.
   */
  pages: {
    /**
     * The action that was performed on the page. Can be `created` or `edited`.
     */
    action: 'created' | 'edited',
    /**
     * Points to the HTML wiki page.
     */
    html_url: string,
    /**
     * The name of the page.
     */
    page_name: string,
    /**
     * The latest commit SHA of the page.
     */
    sha: string,
    summary: string | null
  }[];
  repository: RepositoryWebhooks;
  sender: SimpleUser;
}
