import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser, WebhooksUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OrganizationMemberInvitedEvent {
  action: 'member_invited';
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  /**
   * The invitation for the user or email if the action is `member_invited`.
   */
  invitation: {
    created_at: string,
    email: string | null,
    failed_at: string | null,
    failed_reason: string | null,
    id: number,
    invitation_teams_url: string,
    inviter: {
      avatar_url?: string,
      deleted?: boolean,
      email?: string | null,
      events_url?: string,
      followers_url?: string,
      following_url?: string,
      gists_url?: string,
      gravatar_id?: string,
      html_url?: string,
      id: number,
      login: string,
      name?: string,
      node_id?: string,
      organizations_url?: string,
      received_events_url?: string,
      repos_url?: string,
      site_admin?: boolean,
      starred_url?: string,
      subscriptions_url?: string,
      type?: 'Bot' | 'User' | 'Organization',
      url?: string,
      user_view_type?: string
    } | null,
    login: string | null,
    node_id: string,
    role: string,
    team_count: number,
    invitation_source?: string
  };
  organization: OrganizationSimple;
  repository?: RepositoryWebhooks;
  sender: SimpleUser;
  user?: WebhooksUser;
}
