import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser, WebhooksEffectiveDate, WebhooksSponsorship 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SponsorshipPendingCancellationEvent {
  action: 'pending_cancellation';
  effective_date?: WebhooksEffectiveDate;
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  repository?: RepositoryWebhooks;
  sender: SimpleUser;
  sponsorship: WebhooksSponsorship;
}
