export * from './check_run';
export * from './check_suite';
export * from './code_scanning_alert';
export * from './commit_comment';
export * from './common';
export * from './content_reference';
export * from './deploy_key';
export * from './deployment';
export * from './deployment_status';
export * from './discussion';
export * from './discussion_comment';
export * from './github_app_authorization';
export * from './installation';
export * from './installation_repositories';
export * from './issue_comment';
export * from './issues';
export * from './label';
export * from './marketplace_purchase';
export * from './member';
export * from './membership';
export * from './meta';
export * from './milestone';
export * from './org_block';
export * from './organization';
export * from './package';
export * from './project';
export * from './project_card';
export * from './project_column';
export * from './pull_request';
export * from './pull_request_review';
export * from './pull_request_review_comment';
export * from './release';
export * from './repository';
export * from './repository_dispatch';
export * from './repository_vulnerability_alert';
export * from './secret_scanning_alert';
export * from './security_advisory';
export * from './sponsorship';
export * from './star';
export * from './team';
export * from './watch';
export * from './workflow_run';

import { CheckRunEvent } from './check_run';
import { CheckSuiteEvent } from './check_suite';
import { CodeScanningAlertEvent } from './code_scanning_alert';
import { CommitCommentEvent } from './commit_comment';
import { ContentReferenceEvent } from './content_reference';
import { DeployKeyEvent } from './deploy_key';
import { DeploymentEvent } from './deployment';
import { DeploymentStatusEvent } from './deployment_status';
import { DiscussionEvent } from './discussion';
import { DiscussionCommentEvent } from './discussion_comment';
import { GithubAppAuthorizationEvent } from './github_app_authorization';
import { InstallationEvent } from './installation';
import { InstallationRepositoriesEvent } from './installation_repositories';
import { IssueCommentEvent } from './issue_comment';
import { IssuesEvent } from './issues';
import { LabelEvent } from './label';
import { MarketplacePurchaseEvent } from './marketplace_purchase';
import { MemberEvent } from './member';
import { MembershipEvent } from './membership';
import { MetaEvent } from './meta';
import { MilestoneEvent } from './milestone';
import { OrgBlockEvent } from './org_block';
import { OrganizationEvent } from './organization';
import { PackageEvent } from './package';
import { ProjectEvent } from './project';
import { ProjectCardEvent } from './project_card';
import { ProjectColumnEvent } from './project_column';
import { PullRequestEvent } from './pull_request';
import { PullRequestReviewEvent } from './pull_request_review';
import { PullRequestReviewCommentEvent } from './pull_request_review_comment';
import { ReleaseEvent } from './release';
import { RepositoryEvent } from './repository';
import { RepositoryDispatchEvent } from './repository_dispatch';
import { RepositoryVulnerabilityAlertEvent } from './repository_vulnerability_alert';
import { SecretScanningAlertEvent } from './secret_scanning_alert';
import { SecurityAdvisoryEvent } from './security_advisory';
import { SponsorshipEvent } from './sponsorship';
import { StarEvent } from './star';
import { TeamEvent } from './team';
import { WatchEvent } from './watch';
import { WorkflowRunEvent } from './workflow_run';

export interface EventPayloadMap {
  check_run: CheckRunEvent;
  check_suite: CheckSuiteEvent;
  code_scanning_alert: CodeScanningAlertEvent;
  commit_comment: CommitCommentEvent;
  content_reference: ContentReferenceEvent;
  deploy_key: DeployKeyEvent;
  deployment: DeploymentEvent;
  deployment_status: DeploymentStatusEvent;
  discussion: DiscussionEvent;
  discussion_comment: DiscussionCommentEvent;
  github_app_authorization: GithubAppAuthorizationEvent;
  installation: InstallationEvent;
  installation_repositories: InstallationRepositoriesEvent;
  issue_comment: IssueCommentEvent;
  issues: IssuesEvent;
  label: LabelEvent;
  marketplace_purchase: MarketplacePurchaseEvent;
  member: MemberEvent;
  membership: MembershipEvent;
  meta: MetaEvent;
  milestone: MilestoneEvent;
  org_block: OrgBlockEvent;
  organization: OrganizationEvent;
  package: PackageEvent;
  project: ProjectEvent;
  project_card: ProjectCardEvent;
  project_column: ProjectColumnEvent;
  pull_request: PullRequestEvent;
  pull_request_review: PullRequestReviewEvent;
  pull_request_review_comment: PullRequestReviewCommentEvent;
  release: ReleaseEvent;
  repository: RepositoryEvent;
  repository_dispatch: RepositoryDispatchEvent;
  repository_vulnerability_alert: RepositoryVulnerabilityAlertEvent;
  secret_scanning_alert: SecretScanningAlertEvent;
  security_advisory: SecurityAdvisoryEvent;
  sponsorship: SponsorshipEvent;
  star: StarEvent;
  team: TeamEvent;
  watch: WatchEvent;
  workflow_run: WorkflowRunEvent;
}
