export type * from './branch_protection_configuration/index.d.ts';
export type * from './branch_protection_rule/index.d.ts';
export type * from './check_run/index.d.ts';
export type * from './check_suite/index.d.ts';
export type * from './code_scanning_alert/index.d.ts';
export type * from './commit_comment/index.d.ts';
export type * from './common/index.d.ts';
export type * from './create/index.d.ts';
export type * from './custom_property/index.d.ts';
export type * from './custom_property_values/index.d.ts';
export type * from './delete/index.d.ts';
export type * from './dependabot_alert/index.d.ts';
export type * from './deploy_key/index.d.ts';
export type * from './deployment/index.d.ts';
export type * from './deployment_protection_rule/index.d.ts';
export type * from './deployment_review/index.d.ts';
export type * from './deployment_status/index.d.ts';
export type * from './discussion/index.d.ts';
export type * from './discussion_comment/index.d.ts';
export type * from './fork/index.d.ts';
export type * from './github_app_authorization/index.d.ts';
export type * from './gollum/index.d.ts';
export type * from './installation/index.d.ts';
export type * from './installation_repositories/index.d.ts';
export type * from './installation_target/index.d.ts';
export type * from './issue_comment/index.d.ts';
export type * from './issues/index.d.ts';
export type * from './label/index.d.ts';
export type * from './marketplace_purchase/index.d.ts';
export type * from './member/index.d.ts';
export type * from './membership/index.d.ts';
export type * from './merge_group/index.d.ts';
export type * from './meta/index.d.ts';
export type * from './milestone/index.d.ts';
export type * from './org_block/index.d.ts';
export type * from './organization/index.d.ts';
export type * from './package/index.d.ts';
export type * from './page_build/index.d.ts';
export type * from './personal_access_token_request/index.d.ts';
export type * from './ping/index.d.ts';
export type * from './project/index.d.ts';
export type * from './project_card/index.d.ts';
export type * from './project_column/index.d.ts';
export type * from './projects_v2/index.d.ts';
export type * from './projects_v2_item/index.d.ts';
export type * from './projects_v2_status_update/index.d.ts';
export type * from './public/index.d.ts';
export type * from './pull_request/index.d.ts';
export type * from './pull_request_review/index.d.ts';
export type * from './pull_request_review_comment/index.d.ts';
export type * from './pull_request_review_thread/index.d.ts';
export type * from './push/index.d.ts';
export type * from './registry_package/index.d.ts';
export type * from './release/index.d.ts';
export type * from './repository/index.d.ts';
export type * from './repository_advisory/index.d.ts';
export type * from './repository_dispatch/index.d.ts';
export type * from './repository_import/index.d.ts';
export type * from './repository_ruleset/index.d.ts';
export type * from './repository_vulnerability_alert/index.d.ts';
export type * from './secret_scanning_alert/index.d.ts';
export type * from './secret_scanning_alert_location/index.d.ts';
export type * from './secret_scanning_scan/index.d.ts';
export type * from './security_advisory/index.d.ts';
export type * from './security_and_analysis/index.d.ts';
export type * from './sponsorship/index.d.ts';
export type * from './star/index.d.ts';
export type * from './status/index.d.ts';
export type * from './sub_issues/index.d.ts';
export type * from './team/index.d.ts';
export type * from './team_add/index.d.ts';
export type * from './watch/index.d.ts';
export type * from './workflow_dispatch/index.d.ts';
export type * from './workflow_job/index.d.ts';
export type * from './workflow_run/index.d.ts';

import type { BranchProtectionConfigurationEvent } from './branch_protection_configuration/index.d.ts';
import type { BranchProtectionRuleEvent } from './branch_protection_rule/index.d.ts';
import type { CheckRunEvent } from './check_run/index.d.ts';
import type { CheckSuiteEvent } from './check_suite/index.d.ts';
import type { CodeScanningAlertEvent } from './code_scanning_alert/index.d.ts';
import type { CommitCommentEvent } from './commit_comment/index.d.ts';
import type { CreateEvent } from './create/index.d.ts';
import type { CustomPropertyEvent } from './custom_property/index.d.ts';
import type { CustomPropertyValuesEvent } from './custom_property_values/index.d.ts';
import type { DeleteEvent } from './delete/index.d.ts';
import type { DependabotAlertEvent } from './dependabot_alert/index.d.ts';
import type { DeployKeyEvent } from './deploy_key/index.d.ts';
import type { DeploymentEvent } from './deployment/index.d.ts';
import type { DeploymentProtectionRuleEvent } from './deployment_protection_rule/index.d.ts';
import type { DeploymentReviewEvent } from './deployment_review/index.d.ts';
import type { DeploymentStatusEvent } from './deployment_status/index.d.ts';
import type { DiscussionEvent } from './discussion/index.d.ts';
import type { DiscussionCommentEvent } from './discussion_comment/index.d.ts';
import type { ForkEvent } from './fork/index.d.ts';
import type { GithubAppAuthorizationEvent } from './github_app_authorization/index.d.ts';
import type { GollumEvent } from './gollum/index.d.ts';
import type { InstallationEvent } from './installation/index.d.ts';
import type { InstallationRepositoriesEvent } from './installation_repositories/index.d.ts';
import type { InstallationTargetEvent } from './installation_target/index.d.ts';
import type { IssueCommentEvent } from './issue_comment/index.d.ts';
import type { IssuesEvent } from './issues/index.d.ts';
import type { LabelEvent } from './label/index.d.ts';
import type { MarketplacePurchaseEvent } from './marketplace_purchase/index.d.ts';
import type { MemberEvent } from './member/index.d.ts';
import type { MembershipEvent } from './membership/index.d.ts';
import type { MergeGroupEvent } from './merge_group/index.d.ts';
import type { MetaEvent } from './meta/index.d.ts';
import type { MilestoneEvent } from './milestone/index.d.ts';
import type { OrgBlockEvent } from './org_block/index.d.ts';
import type { OrganizationEvent } from './organization/index.d.ts';
import type { PackageEvent } from './package/index.d.ts';
import type { PageBuildEvent } from './page_build/index.d.ts';
import type { PersonalAccessTokenRequestEvent } from './personal_access_token_request/index.d.ts';
import type { PingEvent } from './ping/index.d.ts';
import type { ProjectEvent } from './project/index.d.ts';
import type { ProjectCardEvent } from './project_card/index.d.ts';
import type { ProjectColumnEvent } from './project_column/index.d.ts';
import type { ProjectsV2Event } from './projects_v2/index.d.ts';
import type { ProjectsV2ItemEvent } from './projects_v2_item/index.d.ts';
import type { ProjectsV2StatusUpdateEvent } from './projects_v2_status_update/index.d.ts';
import type { PublicEvent } from './public/index.d.ts';
import type { PullRequestEvent } from './pull_request/index.d.ts';
import type { PullRequestReviewEvent } from './pull_request_review/index.d.ts';
import type { PullRequestReviewCommentEvent } from './pull_request_review_comment/index.d.ts';
import type { PullRequestReviewThreadEvent } from './pull_request_review_thread/index.d.ts';
import type { PushEvent } from './push/index.d.ts';
import type { RegistryPackageEvent } from './registry_package/index.d.ts';
import type { ReleaseEvent } from './release/index.d.ts';
import type { RepositoryEvent } from './repository/index.d.ts';
import type { RepositoryAdvisoryEvent } from './repository_advisory/index.d.ts';
import type { RepositoryDispatchEvent } from './repository_dispatch/index.d.ts';
import type { RepositoryImportEvent } from './repository_import/index.d.ts';
import type { RepositoryRulesetEvent } from './repository_ruleset/index.d.ts';
import type { RepositoryVulnerabilityAlertEvent } from './repository_vulnerability_alert/index.d.ts';
import type { SecretScanningAlertEvent } from './secret_scanning_alert/index.d.ts';
import type { SecretScanningAlertLocationEvent } from './secret_scanning_alert_location/index.d.ts';
import type { SecretScanningScanEvent } from './secret_scanning_scan/index.d.ts';
import type { SecurityAdvisoryEvent } from './security_advisory/index.d.ts';
import type { SecurityAndAnalysisEvent } from './security_and_analysis/index.d.ts';
import type { SponsorshipEvent } from './sponsorship/index.d.ts';
import type { StarEvent } from './star/index.d.ts';
import type { StatusEvent } from './status/index.d.ts';
import type { SubIssuesEvent } from './sub_issues/index.d.ts';
import type { TeamEvent } from './team/index.d.ts';
import type { TeamAddEvent } from './team_add/index.d.ts';
import type { WatchEvent } from './watch/index.d.ts';
import type { WorkflowDispatchEvent } from './workflow_dispatch/index.d.ts';
import type { WorkflowJobEvent } from './workflow_job/index.d.ts';
import type { WorkflowRunEvent } from './workflow_run/index.d.ts';

export interface EventPayloadMap {
  branch_protection_configuration: BranchProtectionConfigurationEvent;
  branch_protection_rule: BranchProtectionRuleEvent;
  check_run: CheckRunEvent;
  check_suite: CheckSuiteEvent;
  code_scanning_alert: CodeScanningAlertEvent;
  commit_comment: CommitCommentEvent;
  create: CreateEvent;
  custom_property: CustomPropertyEvent;
  custom_property_values: CustomPropertyValuesEvent;
  delete: DeleteEvent;
  dependabot_alert: DependabotAlertEvent;
  deploy_key: DeployKeyEvent;
  deployment: DeploymentEvent;
  deployment_protection_rule: DeploymentProtectionRuleEvent;
  deployment_review: DeploymentReviewEvent;
  deployment_status: DeploymentStatusEvent;
  discussion: DiscussionEvent;
  discussion_comment: DiscussionCommentEvent;
  fork: ForkEvent;
  github_app_authorization: GithubAppAuthorizationEvent;
  gollum: GollumEvent;
  installation: InstallationEvent;
  installation_repositories: InstallationRepositoriesEvent;
  installation_target: InstallationTargetEvent;
  issue_comment: IssueCommentEvent;
  issues: IssuesEvent;
  label: LabelEvent;
  marketplace_purchase: MarketplacePurchaseEvent;
  member: MemberEvent;
  membership: MembershipEvent;
  merge_group: MergeGroupEvent;
  meta: MetaEvent;
  milestone: MilestoneEvent;
  org_block: OrgBlockEvent;
  organization: OrganizationEvent;
  package: PackageEvent;
  page_build: PageBuildEvent;
  personal_access_token_request: PersonalAccessTokenRequestEvent;
  ping: PingEvent;
  project: ProjectEvent;
  project_card: ProjectCardEvent;
  project_column: ProjectColumnEvent;
  projects_v2: ProjectsV2Event;
  projects_v2_item: ProjectsV2ItemEvent;
  projects_v2_status_update: ProjectsV2StatusUpdateEvent;
  public: PublicEvent;
  pull_request: PullRequestEvent;
  pull_request_review: PullRequestReviewEvent;
  pull_request_review_comment: PullRequestReviewCommentEvent;
  pull_request_review_thread: PullRequestReviewThreadEvent;
  push: PushEvent;
  registry_package: RegistryPackageEvent;
  release: ReleaseEvent;
  repository: RepositoryEvent;
  repository_advisory: RepositoryAdvisoryEvent;
  repository_dispatch: RepositoryDispatchEvent;
  repository_import: RepositoryImportEvent;
  repository_ruleset: RepositoryRulesetEvent;
  repository_vulnerability_alert: RepositoryVulnerabilityAlertEvent;
  secret_scanning_alert: SecretScanningAlertEvent;
  secret_scanning_alert_location: SecretScanningAlertLocationEvent;
  secret_scanning_scan: SecretScanningScanEvent;
  security_advisory: SecurityAdvisoryEvent;
  security_and_analysis: SecurityAndAnalysisEvent;
  sponsorship: SponsorshipEvent;
  star: StarEvent;
  status: StatusEvent;
  sub_issues: SubIssuesEvent;
  team: TeamEvent;
  team_add: TeamAddEvent;
  watch: WatchEvent;
  workflow_dispatch: WorkflowDispatchEvent;
  workflow_job: WorkflowJobEvent;
  workflow_run: WorkflowRunEvent;
}
