import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser, WebhooksRelease 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReleaseEditedEvent {
  action: 'edited';
  changes: {
    body?: {
      /**
       * The previous version of the body if the action was `edited`.
       */
      from: string
    },
    name?: {
      /**
       * The previous version of the name if the action was `edited`.
       */
      from: string
    },
    tag_name?: {
      /**
       * The previous version of the tag_name if the action was `edited`.
       */
      from: string
    },
    make_latest?: {
      /**
       * Whether this release was explicitly `edited` to be the latest.
       */
      to: boolean
    }
  };
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  release: WebhooksRelease;
  repository: RepositoryWebhooks;
  sender?: SimpleUser;
}
