import type {
  BranchProtectionRule, EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BranchProtectionRuleEditedEvent {
  action: 'edited';
  /**
   * If the action was `edited`, the changes to the rule.
   */
  changes?: {
    admin_enforced?: {
      from: boolean | null
    },
    authorized_actor_names?: {
      from: string[]
    },
    authorized_actors_only?: {
      from: boolean | null
    },
    authorized_dismissal_actors_only?: {
      from: boolean | null
    },
    linear_history_requirement_enforcement_level?: {
      from: 'off' | 'non_admins' | 'everyone'
    },
    lock_branch_enforcement_level?: {
      from: 'off' | 'non_admins' | 'everyone'
    },
    lock_allows_fork_sync?: {
      from: boolean | null
    },
    pull_request_reviews_enforcement_level?: {
      from: 'off' | 'non_admins' | 'everyone'
    },
    require_last_push_approval?: {
      from: boolean | null
    },
    required_status_checks?: {
      from: string[]
    },
    required_status_checks_enforcement_level?: {
      from: 'off' | 'non_admins' | 'everyone'
    }
  };
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  repository: RepositoryWebhooks;
  rule: BranchProtectionRule;
  sender: SimpleUser;
}
