import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProjectCardMovedEvent {
  action: 'moved';
  changes?: {
    column_id: {
      from: number
    }
  };
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  project_card: {
    after_id?: number | null,
    /**
     * Whether or not the card is archived
     */
    archived: boolean,
    column_id: number,
    column_url: string,
    content_url?: string,
    created_at: string,
    creator: {
      avatar_url?: string,
      deleted?: boolean,
      email?: string | null,
      events_url?: string,
      followers_url?: string,
      following_url?: string,
      gists_url?: string,
      gravatar_id?: string,
      html_url?: string,
      id: number,
      login: string,
      name?: string,
      node_id?: string,
      organizations_url?: string,
      received_events_url?: string,
      repos_url?: string,
      site_admin?: boolean,
      starred_url?: string,
      subscriptions_url?: string,
      type?: 'Bot' | 'User' | 'Organization' | 'Mannequin',
      url?: string,
      user_view_type?: string
    } | null,
    /**
     * The project card's ID
     */
    id: number,
    node_id: string,
    note: string | null,
    project_url: string,
    updated_at: string,
    url: string
  } & {
    after_id: number | null,
    archived?: boolean,
    column_id?: number,
    column_url?: string,
    created_at?: string,
    creator?: {
      avatar_url?: string,
      events_url?: string,
      followers_url?: string,
      following_url?: string,
      gists_url?: string,
      gravatar_id?: string,
      html_url?: string,
      id?: number,
      login?: string,
      node_id?: string,
      organizations_url?: string,
      received_events_url?: string,
      repos_url?: string,
      site_admin?: boolean,
      starred_url?: string,
      subscriptions_url?: string,
      type?: string,
      url?: string
    } | null,
    id?: number,
    node_id?: string,
    note?: string | null,
    project_url?: string,
    updated_at?: string,
    url?: string
  };
  repository?: RepositoryWebhooks;
  sender: SimpleUser;
}
