import type {
  OrganizationSimple, ProjectsV2StatusUpdate, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProjectsV2StatusUpdateEditedEvent {
  action: 'edited';
  changes?: {
    body?: {
      from?: string | null,
      to?: string | null
    },
    status?: {
      from?:
        | (
            | 'INACTIVE'
            | 'ON_TRACK'
            | 'AT_RISK'
            | 'OFF_TRACK'
            | 'COMPLETE'
            | null
          )
        | null,
      to?:
        | (
            | 'INACTIVE'
            | 'ON_TRACK'
            | 'AT_RISK'
            | 'OFF_TRACK'
            | 'COMPLETE'
            | null
          )
        | null
    },
    start_date?: {
      from?: string | null,
      to?: string | null
    },
    target_date?: {
      from?: string | null,
      to?: string | null
    }
  };
  installation?: SimpleInstallation;
  organization: OrganizationSimple;
  projects_v2_status_update: ProjectsV2StatusUpdate;
  sender: SimpleUser;
}
