import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, WebhooksTeam, WebhooksUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MembershipAddedEvent {
  action: 'added';
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  member: WebhooksUser;
  organization: OrganizationSimple;
  repository?: RepositoryWebhooks;
  /**
   * The scope of the membership. Currently, can only be `team`.
   */
  scope: 'team';
  sender: {
    avatar_url?: string,
    deleted?: boolean,
    email?: string | null,
    events_url?: string,
    followers_url?: string,
    following_url?: string,
    gists_url?: string,
    gravatar_id?: string,
    html_url?: string,
    id: number,
    login: string,
    name?: string,
    node_id?: string,
    organizations_url?: string,
    received_events_url?: string,
    repos_url?: string,
    site_admin?: boolean,
    starred_url?: string,
    subscriptions_url?: string,
    type?: 'Bot' | 'User' | 'Organization',
    url?: string,
    user_view_type?: string
  } | null;
  team: WebhooksTeam;
}
