import type {
  DeploymentSimple, GitHubApp, PullRequestMinimal, SimpleCheckSuite 
} from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A check performed on the code of a given code change
 */
export interface CheckRun {
  app: null | GitHubApp;
  check_suite: SimpleCheckSuite;
  completed_at: string | null;
  conclusion:
    | (
        | 'waiting'
        | 'pending'
        | 'startup_failure'
        | 'stale'
        | 'success'
        | 'failure'
        | 'neutral'
        | 'cancelled'
        | 'skipped'
        | 'timed_out'
        | 'action_required'
        | null
      )
    | null;
  deployment?: DeploymentSimple;
  details_url: string;
  external_id: string;
  /**
   * The SHA of the commit that is being checked.
   */
  head_sha: string;
  html_url: string;
  /**
   * The id of the check.
   */
  id: number;
  /**
   * The name of the check.
   */
  name: string;
  node_id: string;
  output: {
    annotations_count: number,
    annotations_url: string,
    summary: string | null,
    text: string | null
  };
  pull_requests: PullRequestMinimal[];
  started_at: string;
  /**
   * The phase of the lifecycle that the check is currently in.
   */
  status: 'queued' | 'in_progress' | 'completed' | 'pending';
  url: string;
}
