/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Code of Conduct Simple
 */
export interface CodeOfConductSimple {
  url: string;
  key: string;
  name: string;
  html_url: string | null;
}
