/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Custom property defined on an organization
 */
export interface OrganizationCustomProperty {
  /**
   * The name of the property
   */
  property_name: string;
  /**
   * The URL that can be used to fetch, update, or delete info about this property via the API.
   */
  url?: string;
  /**
   * The source type of the property
   */
  source_type?: 'organization' | 'enterprise';
  /**
   * The type of the value for the property
   */
  value_type: 'string' | 'single_select' | 'multi_select' | 'true_false';
  /**
   * Whether the property is required.
   */
  required?: boolean;
  /**
   * Default value of the property
   */
  default_value?: string | string[] | null;
  description?: string | null;
  allowed_values?: string[] | null;
  values_editable_by?: ('org_actors' | 'org_and_repo_actors' | null) | null;
}
