/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CvssSeverities {
  cvss_v3?: {
    /**
     * The CVSS 3 vector string.
     */
    vector_string: string | null,
    /**
     * The CVSS 3 score.
     */
    score: number | null
  } | null;
  cvss_v4?: {
    /**
     * The CVSS 4 vector string.
     */
    vector_string: string | null,
    /**
     * The CVSS 4 score.
     */
    score: number | null
  } | null;
}
