import type {
  AlertAutoDismissedAt, AlertCreatedAt, AlertDismissedAt, AlertFixedAt, AlertHtmlUrl, AlertNumber, AlertUpdatedAt, AlertUrl, DependabotAlertPackage, DependabotAlertSecurityAdvisory, DependabotAlertSecurityVulnerability, SimpleUser 
} from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A Dependabot alert.
 */
export interface DependabotAlert {
  number: AlertNumber;
  /**
   * The state of the Dependabot alert.
   */
  state: 'auto_dismissed' | 'dismissed' | 'fixed' | 'open';
  /**
   * Details for the vulnerable dependency.
   */
  dependency: {
    package?: DependabotAlertPackage,
    /**
     * The full path to the dependency manifest file, relative to the root of the repository.
     */
    manifest_path?: string,
    /**
     * The execution scope of the vulnerable dependency.
     */
    scope?: ('development' | 'runtime' | null) | null,
    /**
     * The vulnerable dependency's relationship to your project.
     *
     * > [!NOTE]
     * > We are rolling out support for dependency relationship across ecosystems. This value will be "unknown" for all dependencies in unsupported ecosystems.
     *
     */
    relationship?: ('unknown' | 'direct' | 'transitive' | null) | null
  };
  security_advisory: DependabotAlertSecurityAdvisory;
  security_vulnerability: DependabotAlertSecurityVulnerability;
  url: AlertUrl;
  html_url: AlertHtmlUrl;
  created_at: AlertCreatedAt;
  updated_at: AlertUpdatedAt;
  dismissed_at: AlertDismissedAt;
  dismissed_by: null | SimpleUser;
  /**
   * The reason that the alert was dismissed.
   */
  dismissed_reason:
    | (
        | 'fix_started'
        | 'inaccurate'
        | 'no_bandwidth'
        | 'not_used'
        | 'tolerable_risk'
        | null
      )
    | null;
  /**
   * An optional comment associated with the alert's dismissal.
   */
  dismissed_comment: string | null;
  fixed_at: AlertFixedAt;
  auto_dismissed_at?: AlertAutoDismissedAt;
}
