import type {
  CvssSeverities, DependabotAlertSecurityVulnerability, SecurityAdvisoryEpss 
} from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Details for the GitHub Security Advisory.
 */
export interface DependabotAlertSecurityAdvisory {
  /**
   * The unique GitHub Security Advisory ID assigned to the advisory.
   */
  ghsa_id: string;
  cve_id: string | null;
  /**
   * A short, plain text summary of the advisory.
   */
  summary: string;
  /**
   * A long-form Markdown-supported description of the advisory.
   */
  description: string;
  /**
   * Vulnerable version range information for the advisory.
   */
  vulnerabilities: DependabotAlertSecurityVulnerability[];
  /**
   * The severity of the advisory.
   */
  severity: 'low' | 'medium' | 'high' | 'critical';
  /**
   * Details for the advisory pertaining to the Common Vulnerability Scoring System.
   */
  cvss: {
    /**
     * The overall CVSS score of the advisory.
     */
    score: number,
    vector_string: string | null
  };
  cvss_severities?: CvssSeverities;
  epss?: SecurityAdvisoryEpss;
  /**
   * Details for the advisory pertaining to Common Weakness Enumeration.
   */
  cwes: {
    /**
     * The unique CWE ID.
     */
    cwe_id: string,
    /**
     * The short, plain text name of the CWE.
     */
    name: string
  }[];
  /**
   * Values that identify this advisory among security information sources.
   */
  identifiers: {
    /**
     * The type of advisory identifier.
     */
    type: 'CVE' | 'GHSA',
    /**
     * The value of the advisory identifer.
     */
    value: string
  }[];
  /**
   * Links to additional advisory information.
   */
  references: {
    /**
     * The URL of the reference.
     */
    url: string
  }[];
  /**
   * The time that the advisory was published in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
   */
  published_at: string;
  /**
   * The time that the advisory was last modified in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
   */
  updated_at: string;
  withdrawn_at: string | null;
}
