/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IssueType {
  /**
   * The unique identifier of the issue type.
   */
  id: number;
  /**
   * The node identifier of the issue type.
   */
  node_id: string;
  /**
   * The name of the issue type.
   */
  name: string;
  /**
   * The description of the issue type.
   */
  description: string | null;
  /**
   * The color of the issue type.
   */
  color?:
    | (
        | 'gray'
        | 'blue'
        | 'green'
        | 'yellow'
        | 'orange'
        | 'red'
        | 'pink'
        | 'purple'
        | null
      )
    | null;
  /**
   * The time the issue type created.
   */
  created_at?: string;
  /**
   * The time the issue type last updated.
   */
  updated_at?: string;
  /**
   * The enabled state of the issue type.
   */
  is_enabled?: boolean;
}
