import type {
  AuthorAssociation, GitHubApp, IssueType, Milestone, ReactionRollup, Repository, SimpleUser, SubIssuesSummary 
} from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Issues are a great way to keep track of tasks, enhancements, and bugs for your projects.
 */
export interface Issue {
  id: number;
  node_id: string;
  /**
   * URL for the issue
   */
  url: string;
  repository_url: string;
  labels_url: string;
  comments_url: string;
  events_url: string;
  html_url: string;
  /**
   * Number uniquely identifying the issue within its repository
   */
  number: number;
  /**
   * State of the issue; either 'open' or 'closed'
   */
  state: string;
  state_reason?: ('completed' | 'reopened' | 'not_planned' | null) | null;
  body?: string | null;
  user: null | SimpleUser;
  /**
   * Labels to associate with this issue; pass one or more label names to replace the set of labels on this issue; send an empty array to clear all labels from the issue; note that the labels are silently dropped for users without push access to the repository
   */
  labels: (
    | string
    | {
      id?: number,
      node_id?: string,
      url?: string,
      name?: string,
      description?: string | null,
      color?: string | null,
      default?: boolean
    }
  )[];
  assignee: null | SimpleUser;
  assignees?: SimpleUser[] | null;
  milestone: null | Milestone;
  locked: boolean;
  active_lock_reason?: string | null;
  comments: number;
  pull_request?: {
    merged_at?: string | null,
    diff_url: string | null,
    html_url: string | null,
    patch_url: string | null,
    url: string | null
  };
  closed_at: string | null;
  created_at: string;
  updated_at: string;
  draft?: boolean;
  closed_by?: null | SimpleUser;
  body_html?: string;
  body_text?: string;
  timeline_url?: string;
  type?: IssueType;
  repository?: Repository;
  performed_via_github_app?: null | GitHubApp;
  author_association: AuthorAssociation;
  reactions?: ReactionRollup;
  sub_issues_summary?: SubIssuesSummary;
}
