import type { SimpleCommit } from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A group of pull requests that the merge queue has grouped together to be merged.
 */
export interface MergeGroup {
  /**
   * The SHA of the merge group.
   */
  head_sha: string;
  /**
   * The full ref of the merge group.
   */
  head_ref: string;
  /**
   * The SHA of the merge group's parent commit.
   */
  base_sha: string;
  /**
   * The full ref of the branch the merge group will be merged into.
   */
  base_ref: string;
  head_commit: SimpleCommit;
}
