import type {
  RepositoryRulesetConditionsForRefNames, RepositoryRulesetConditionsForRepositoryIDs, RepositoryRulesetConditionsForRepositoryNames, RepositoryRulesetConditionsForRepositoryProperties 
} from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Conditions for an organization ruleset.
 * The branch and tag rulesets conditions object should contain both `repository_name` and `ref_name` properties, or both `repository_id` and `ref_name` properties, or both `repository_property` and `ref_name` properties.
 * The push rulesets conditions object does not require the `ref_name` property.
 * For repository policy rulesets, the conditions object should only contain the `repository_name`, the `repository_id`, or the `repository_property`.
 */
export type OrganizationRulesetConditions =
  | (RepositoryRulesetConditionsForRefNames &
      RepositoryRulesetConditionsForRepositoryNames)
  | (RepositoryRulesetConditionsForRefNames &
      RepositoryRulesetConditionsForRepositoryIDs)
  | (RepositoryRulesetConditionsForRefNames &
      RepositoryRulesetConditionsForRepositoryProperties);
