/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PackageNugetMetadata {
  id?: number | string;
  name?: string;
  value?:
    | boolean
    | number
    | string
    | {
      url?: string,
      branch?: string,
      commit?: string,
      type?: string
    };
}
