/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PackageNPMMetadata {
  name?: string;
  version?: string;
  npm_user?: string;
  author?: Record<string, string> | null;
  bugs?: Record<string, string> | null;
  dependencies?: Record<string, string>;
  dev_dependencies?: Record<string, string>;
  peer_dependencies?: Record<string, string>;
  optional_dependencies?: Record<string, string>;
  description?: string;
  dist?: Record<string, string> | null;
  git_head?: string;
  homepage?: string;
  license?: string;
  main?: string;
  repository?: Record<string, string> | null;
  scripts?: Record<string, unknown>;
  id?: string;
  node_version?: string;
  npm_version?: string;
  has_shrinkwrap?: boolean;
  maintainers?: Record<string, unknown>[];
  contributors?: Record<string, unknown>[];
  engines?: Record<string, string>;
  keywords?: string[];
  files?: string[];
  bin?: Record<string, unknown>;
  man?: Record<string, unknown>;
  directories?: Record<string, string> | null;
  os?: string[];
  cpu?: string[];
  readme?: string;
  installation_command?: string;
  release_id?: number;
  commit_oid?: string;
  published_via_actions?: boolean;
  deleted_by_id?: number;
}
