/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An iteration setting for an iteration field
 */
export interface ProjectsV2IterationSetting {
  id: string;
  duration?: number | null;
  start_date?: string | null;
}
