import type { ProjectsV2ItemContentType, SimpleUser } from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An item belonging to a project
 */
export interface ProjectsV2Item {
  id: number;
  node_id?: string;
  project_node_id?: string;
  content_node_id: string;
  content_type: ProjectsV2ItemContentType;
  creator?: SimpleUser;
  created_at: string;
  updated_at: string;
  archived_at: string | null;
}
