import type { SimpleUser } from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An status update belonging to a project
 */
export interface ProjectsV2StatusUpdate {
  id: number;
  node_id: string;
  project_node_id?: string;
  creator?: SimpleUser;
  created_at: string;
  updated_at: string;
  status?:
    | ('INACTIVE' | 'ON_TRACK' | 'AT_RISK' | 'OFF_TRACK' | 'COMPLETE' | null)
    | null;
  start_date?: string;
  target_date?: string;
  body?: string | null;
}
