import type { SimpleUser } from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A projects v2 project
 */
export interface ProjectsV2Project {
  id: number;
  node_id: string;
  owner: SimpleUser;
  creator: SimpleUser;
  description: string | null;
  public: boolean;
  closed_at: string | null;
  created_at: string;
  updated_at: string;
  number: number;
  short_description: string | null;
  deleted_at: string | null;
  deleted_by: null | SimpleUser;
}
