/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An option for a single select field
 */
export interface ProjectsV2SingleSelectOption {
  id: string;
  name: string;
  color?: string | null;
  description?: string | null;
}
