import type {
  AuthorAssociation, AutoMerge, Link, Milestone, Repository, SimpleUser, TeamSimple 
} from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Pull requests let you tell others about changes you've pushed to a repository on GitHub. Once a pull request is sent, interested parties can review the set of changes, discuss potential modifications, and even push follow-up commits if necessary.
 */
export interface PullRequest {
  url: string;
  id: number;
  node_id: string;
  html_url: string;
  diff_url: string;
  patch_url: string;
  issue_url: string;
  commits_url: string;
  review_comments_url: string;
  review_comment_url: string;
  comments_url: string;
  statuses_url: string;
  /**
   * Number uniquely identifying the pull request within its repository.
   */
  number: number;
  /**
   * State of this Pull Request. Either `open` or `closed`.
   */
  state: 'open' | 'closed';
  locked: boolean;
  user: SimpleUser;
  body: string | null;
  labels: {
    id: number,
    node_id: string,
    url: string,
    name: string,
    description: string | null,
    color: string,
    default: boolean
  }[];
  milestone: null | Milestone;
  active_lock_reason?: string | null;
  created_at: string;
  updated_at: string;
  closed_at: string | null;
  merged_at: string | null;
  merge_commit_sha: string | null;
  assignee: null | SimpleUser;
  assignees?: SimpleUser[] | null;
  requested_reviewers?: SimpleUser[] | null;
  requested_teams?: TeamSimple[] | null;
  head: {
    label: string,
    ref: string,
    repo: Repository,
    sha: string,
    user: SimpleUser
  };
  base: {
    label: string,
    ref: string,
    repo: Repository,
    sha: string,
    user: SimpleUser
  };
  _links: {
    comments: Link,
    commits: Link,
    statuses: Link,
    html: Link,
    issue: Link,
    review_comments: Link,
    review_comment: Link,
    self: Link
  };
  author_association: AuthorAssociation;
  auto_merge: AutoMerge;
  /**
   * Indicates whether or not the pull request is a draft.
   */
  draft?: boolean;
  merged: boolean;
  mergeable: boolean | null;
  rebaseable?: boolean | null;
  mergeable_state: string;
  merged_by: null | SimpleUser;
  comments: number;
  review_comments: number;
  /**
   * Indicates whether maintainers can modify the pull request.
   */
  maintainer_can_modify: boolean;
  commits: number;
  additions: number;
  deletions: number;
  changed_files: number;
}
