/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Required status check
 */
export interface StatusCheckConfiguration {
  /**
   * The status check context name that must be present on the commit.
   */
  context: string;
  /**
   * The optional integration ID that this status check must originate from.
   */
  integration_id?: number;
}
