/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Only allow users with bypass permissions to delete matching refs.
 */
export interface Deletion {
  type: 'deletion';
}
