import type { StatusCheckConfiguration } from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Choose which status checks must pass before the ref is updated. When enabled, commits must first be pushed to another ref where the checks pass.
 */
export interface RequiredStatusChecks {
  type: 'required_status_checks';
  parameters?: {
    /**
     * Allow repositories and branches to be created if a check would otherwise prohibit it.
     */
    do_not_enforce_on_create?: boolean,
    /**
     * Status checks that are required.
     */
    required_status_checks: StatusCheckConfiguration[],
    /**
     * Whether pull requests targeting a matching branch must be tested with the latest code. This setting will not take effect unless at least one status check is enabled.
     */
    strict_required_status_checks_policy: boolean
  };
}
