/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Parameters for a repository name condition
 */
export interface RepositoryRulesetConditionsForRepositoryNames {
  repository_name: {
    /**
     * Array of repository names or patterns to include. One of these patterns must match for the condition to pass. Also accepts `~ALL` to include all repositories.
     */
    include?: string[],
    /**
     * Array of repository names or patterns to exclude. The condition will not pass if any of these patterns match.
     */
    exclude?: string[],
    /**
     * Whether renaming of target repositories is prevented.
     */
    protected?: boolean
  };
}
