/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Prevent commits with individual files that exceed the specified limit from being pushed to the commit graph.
 */
export interface MaxFileSize {
  type: 'max_file_size';
  parameters?: {
    /**
     * The maximum file size allowed in megabytes. This limit does not apply to Git Large File Storage (Git LFS).
     */
    max_file_size: number
  };
}
