/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Prevent commits that include changes in specified file and folder paths from being pushed to the commit graph. This includes absolute paths that contain file names.
 */
export interface FilePathRestriction {
  type: 'file_path_restriction';
  parameters?: {
    /**
     * The file paths that are restricted from being pushed to the commit graph.
     */
    restricted_file_paths: string[]
  };
}
