/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An actor that can bypass rules in a ruleset
 */
export interface RepositoryRulesetBypassActor {
  /**
   * The ID of the actor that can bypass a ruleset. If `actor_type` is `OrganizationAdmin`, this should be `1`. If `actor_type` is `DeployKey`, this should be null. `OrganizationAdmin` is not applicable for personal repositories.
   */
  actor_id?: number | null;
  /**
   * The type of actor that can bypass a ruleset.
   */
  actor_type:
    | 'Integration'
    | 'OrganizationAdmin'
    | 'RepositoryRole'
    | 'Team'
    | 'DeployKey';
  /**
   * When the specified actor can bypass the ruleset. `pull_request` means that an actor can only bypass rules on pull requests. `pull_request` is not applicable for the `DeployKey` actor type. Also, `pull_request` is only applicable to branch rulesets.
   */
  bypass_mode?: 'always' | 'pull_request';
}
