import type { RepositoryRulesetPropertyTargetingDefinition } from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Parameters for a repository property condition
 */
export interface RepositoryRulesetConditionsForRepositoryProperties {
  repository_property: {
    /**
     * The repository properties and values to include. All of these properties must match for the condition to pass.
     */
    include?: RepositoryRulesetPropertyTargetingDefinition[],
    /**
     * The repository properties and values to exclude. The condition will not pass if any of these properties match.
     */
    exclude?: RepositoryRulesetPropertyTargetingDefinition[]
  };
}
