/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Prevent commits that include file paths that exceed the specified character limit from being pushed to the commit graph.
 */
export interface MaxFilePathLength {
  type: 'max_file_path_length';
  parameters?: {
    /**
     * The maximum amount of characters allowed in file paths.
     */
    max_file_path_length: number
  };
}
