/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Require all commits be made to a non-target branch and submitted via a pull request before they can be merged.
 */
export interface RepositoryRulePullRequest {
  type: 'pull_request';
  parameters?: {
    /**
     * Array of allowed merge methods. Allowed values include `merge`, `squash`, and `rebase`. At least one option must be enabled.
     */
    allowed_merge_methods?: ('merge' | 'squash' | 'rebase')[],
    /**
     * Automatically request review from Copilot for new pull requests, if the author has access to Copilot code review.
     */
    automatic_copilot_code_review_enabled?: boolean,
    /**
     * New, reviewable commits pushed will dismiss previous pull request review approvals.
     */
    dismiss_stale_reviews_on_push: boolean,
    /**
     * Require an approving review in pull requests that modify files that have a designated code owner.
     */
    require_code_owner_review: boolean,
    /**
     * Whether the most recent reviewable push must be approved by someone other than the person who pushed it.
     */
    require_last_push_approval: boolean,
    /**
     * The number of approving reviews that are required before a pull request can be merged.
     */
    required_approving_review_count: number,
    /**
     * All conversations on code must be resolved before a pull request can be merged.
     */
    required_review_thread_resolution: boolean
  };
}
