/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Parameters for a repository ID condition
 */
export interface RepositoryRulesetConditionsForRepositoryIDs {
  repository_id: {
    /**
     * The repository IDs that the ruleset applies to. One of these IDs must match for the condition to pass.
     */
    repository_ids?: number[]
  };
}
