/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Choose which environments must be successfully deployed to before refs can be pushed into a ref that matches this rule.
 */
export interface RequiredDeployments {
  type: 'required_deployments';
  parameters?: {
    /**
     * The environments that must be successfully deployed to before branches can be merged.
     */
    required_deployment_environments: string[]
  };
}
