import type { SecurityAdvisoryCreditTypes, SimpleUser } from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A credit given to a user for a repository security advisory.
 */
export interface RepositoryAdvisoryCredit {
  user: SimpleUser;
  type: SecurityAdvisoryCreditTypes;
  /**
   * The state of the user's acceptance of the credit.
   */
  state: 'accepted' | 'declined' | 'pending';
}
