import type { CodeScanningTool } from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Choose which tools must provide code scanning results before the reference is updated. When configured, code scanning must be enabled and have results for both the commit and the reference being updated.
 */
export interface CodeScanning {
  type: 'code_scanning';
  parameters?: {
    /**
     * Tools that must provide code scanning results for this rule to pass.
     */
    code_scanning_tools: CodeScanningTool[]
  };
}
