/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Parameters to be used for the branch_name_pattern rule
 */
export interface BranchNamePattern {
  type: 'branch_name_pattern';
  parameters?: {
    /**
     * How this rule will appear to users.
     */
    name?: string,
    /**
     * If true, the rule will fail if the pattern matches.
     */
    negate?: boolean,
    /**
     * The operator to use for matching.
     */
    operator: 'starts_with' | 'ends_with' | 'contains' | 'regex',
    /**
     * The pattern to match with.
     */
    pattern: string
  };
}
