import type { WorkflowFileReference } from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Require all changes made to a targeted branch to pass the specified workflows before they can be merged.
 */
export interface Workflows {
  type: 'workflows';
  parameters?: {
    /**
     * Allow repositories and branches to be created if a check would otherwise prohibit it.
     */
    do_not_enforce_on_create?: boolean,
    /**
     * Workflows that must pass for this rule to pass.
     */
    workflows: WorkflowFileReference[]
  };
}
