/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Prevent commits that include files with specified file extensions from being pushed to the commit graph.
 */
export interface FileExtensionRestriction {
  type: 'file_extension_restriction';
  parameters?: {
    /**
     * The file extensions that are restricted from being pushed to the commit graph.
     */
    restricted_file_extensions: string[]
  };
}
