import type {
  CvssSeverities, RepositoryAdvisoryCredit, RepositoryAdvisoryVulnerability, SecurityAdvisoryCreditTypes, SimpleRepository, SimpleUser, Team 
} from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A repository security advisory.
 */
export interface RepositoryAdvisory {
  /**
   * The GitHub Security Advisory ID.
   */
  ghsa_id: string;
  cve_id: string | null;
  /**
   * The API URL for the advisory.
   */
  url: string;
  /**
   * The URL for the advisory.
   */
  html_url: string;
  /**
   * A short summary of the advisory.
   */
  summary: string;
  description: string | null;
  severity: ('critical' | 'high' | 'medium' | 'low' | null) | null;
  /**
   * The author of the advisory.
   */
  author: SimpleUser & null;
  /**
   * The publisher of the advisory.
   */
  publisher: SimpleUser & null;
  identifiers: {
    /**
     * The type of identifier.
     */
    type: 'CVE' | 'GHSA',
    /**
     * The identifier value.
     */
    value: string
  }[];
  /**
   * The state of the advisory.
   */
  state: 'published' | 'closed' | 'withdrawn' | 'draft' | 'triage';
  created_at: string | null;
  updated_at: string | null;
  published_at: string | null;
  closed_at: string | null;
  withdrawn_at: string | null;
  submission: {
    /**
     * Whether a private vulnerability report was accepted by the repository's administrators.
     */
    accepted: boolean
  } | null;
  vulnerabilities: RepositoryAdvisoryVulnerability[] | null;
  cvss: {
    vector_string: string | null,
    score: number | null
  } | null;
  cvss_severities?: CvssSeverities;
  cwes:
    | {
      /**
       * The Common Weakness Enumeration (CWE) identifier.
       */
      cwe_id: string,
      /**
       * The name of the CWE.
       */
      name: string
    }[]
    | null;
  cwe_ids: string[] | null;
  credits:
    | {
      /**
       * The username of the user credited.
       */
      login?: string,
      type?: SecurityAdvisoryCreditTypes
    }[]
    | null;
  credits_detailed: RepositoryAdvisoryCredit[] | null;
  collaborating_users: SimpleUser[] | null;
  collaborating_teams: Team[] | null;
  /**
   * A temporary private fork of the advisory's repository for collaborating on a fix.
   */
  private_fork: SimpleRepository & null;
}
