/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Only allow users with bypass permission to update matching refs.
 */
export interface Update {
  type: 'update';
  parameters?: {
    /**
     * Branch can pull changes from its upstream repository
     */
    update_allows_fetch_and_merge: boolean
  };
}
