/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Parameters for a targeting a repository property
 */
export interface RepositoryRulesetPropertyTargetingDefinition {
  /**
   * The name of the repository property to target
   */
  name: string;
  /**
   * The values to match for the repository property
   */
  property_values: string[];
  /**
   * The source of the repository property. Defaults to 'custom' if not specified.
   */
  source?: 'custom' | 'system';
}
