/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Commits pushed to matching refs must have verified signatures.
 */
export interface RequiredSignatures {
  type: 'required_signatures';
}
