import type {
  BranchNamePattern, CodeScanning, CommitAuthorEmailPattern, CommitMessagePattern, CommitterEmailPattern, Creation, Deletion, FileExtensionRestriction, FilePathRestriction, MaxFilePathLength, MaxFileSize, MergeQueue, NonFastForward, RepositoryRulePullRequest, RequiredDeployments, RequiredLinearHistory, RequiredSignatures, RequiredStatusChecks, TagNamePattern, Update, Workflows 
} from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A repository rule.
 */
export type RepositoryRule =
  | Creation
  | Update
  | Deletion
  | RequiredLinearHistory
  | MergeQueue
  | RequiredDeployments
  | RequiredSignatures
  | RepositoryRulePullRequest
  | RequiredStatusChecks
  | NonFastForward
  | CommitMessagePattern
  | CommitAuthorEmailPattern
  | CommitterEmailPattern
  | BranchNamePattern
  | TagNamePattern
  | FilePathRestriction
  | MaxFilePathLength
  | FileExtensionRestriction
  | MaxFileSize
  | Workflows
  | CodeScanning;
