/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Parameters for a repository ruleset ref name condition
 */
export interface RepositoryRulesetConditionsForRefNames {
  ref_name?: {
    /**
     * Array of ref names or patterns to include. One of these patterns must match for the condition to pass. Also accepts `~DEFAULT_BRANCH` to include the default branch or `~ALL` to include all branches.
     */
    include?: string[],
    /**
     * Array of ref names or patterns to exclude. The condition will not pass if any of these patterns match.
     */
    exclude?: string[]
  };
}
