import type {
  SecretScanningLocationCommit, SecretScanningLocationDiscussionBody, SecretScanningLocationDiscussionComment, SecretScanningLocationDiscussionTitle, SecretScanningLocationIssueBody, SecretScanningLocationIssueComment, SecretScanningLocationIssueTitle, SecretScanningLocationPullRequestBody, SecretScanningLocationPullRequestComment, SecretScanningLocationPullRequestReview, SecretScanningLocationPullRequestReviewComment, SecretScanningLocationPullRequestTitle, SecretScanningLocationWikiCommit 
} from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SecretScanningLocation {
  /**
   * The location type. Because secrets may be found in different types of resources (ie. code, comments, issues, pull requests, discussions), this field identifies the type of resource where the secret was found.
   */
  type?:
    | 'commit'
    | 'wiki_commit'
    | 'issue_title'
    | 'issue_body'
    | 'issue_comment'
    | 'discussion_title'
    | 'discussion_body'
    | 'discussion_comment'
    | 'pull_request_title'
    | 'pull_request_body'
    | 'pull_request_comment'
    | 'pull_request_review'
    | 'pull_request_review_comment';
  details?:
    | SecretScanningLocationCommit
    | SecretScanningLocationWikiCommit
    | SecretScanningLocationIssueTitle
    | SecretScanningLocationIssueBody
    | SecretScanningLocationIssueComment
    | SecretScanningLocationDiscussionTitle
    | SecretScanningLocationDiscussionBody
    | SecretScanningLocationDiscussionComment
    | SecretScanningLocationPullRequestTitle
    | SecretScanningLocationPullRequestBody
    | SecretScanningLocationPullRequestComment
    | SecretScanningLocationPullRequestReview
    | SecretScanningLocationPullRequestReviewComment;
}
