/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a 'pull_request_review' secret scanning location type. This location type shows that a secret was detected in a review on a pull request.
 */
export interface SecretScanningLocationPullRequestReview {
  /**
   * The API URL to get the pull request review where the secret was detected.
   */
  pull_request_review_url: string;
}
