/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a 'discussion_comment' secret scanning location type. This location type shows that a secret was detected in a comment on a discussion.
 */
export interface SecretScanningLocationDiscussionComment {
  /**
   * The API URL to get the discussion comment where the secret was detected.
   */
  discussion_comment_url: string;
}
