/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The reason for resolving the alert.
 */
export type SecretScanningAlertResolutionWebhook =
  | 'false_positive'
  | 'wont_fix'
  | 'revoked'
  | 'used_in_tests'
  | 'pattern_deleted'
  | 'pattern_edited'
  | null;
