/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The type of credit the user is receiving.
 */
export type SecurityAdvisoryCreditTypes =
  | 'analyst'
  | 'finder'
  | 'reporter'
  | 'coordinator'
  | 'remediation_developer'
  | 'remediation_reviewer'
  | 'remediation_verifier'
  | 'tool'
  | 'sponsor'
  | 'other';
