/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SecurityAndAnalysis {
  advanced_security?: {
    status?: 'enabled' | 'disabled'
  };
  code_security?: {
    status?: 'enabled' | 'disabled'
  };
  /**
   * Enable or disable Dependabot security updates for the repository.
   */
  dependabot_security_updates?: {
    /**
     * The enablement status of Dependabot security updates for the repository.
     */
    status?: 'enabled' | 'disabled'
  };
  secret_scanning?: {
    status?: 'enabled' | 'disabled'
  };
  secret_scanning_push_protection?: {
    status?: 'enabled' | 'disabled'
  };
  secret_scanning_non_provider_patterns?: {
    status?: 'enabled' | 'disabled'
  };
  secret_scanning_ai_detection?: {
    status?: 'enabled' | 'disabled'
  };
}
