import type {
  GitHubApp, MinimalRepository, PullRequestMinimal 
} from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A suite of checks performed on the code of a given code change
 */
export interface SimpleCheckSuite {
  after?: string | null;
  app?: GitHubApp;
  before?: string | null;
  conclusion?:
    | (
        | 'success'
        | 'failure'
        | 'neutral'
        | 'cancelled'
        | 'skipped'
        | 'timed_out'
        | 'action_required'
        | 'stale'
        | 'startup_failure'
        | null
      )
    | null;
  created_at?: string;
  head_branch?: string | null;
  /**
   * The SHA of the head commit that is being checked.
   */
  head_sha?: string;
  id?: number;
  node_id?: string;
  pull_requests?: PullRequestMinimal[];
  repository?: MinimalRepository;
  status?: 'queued' | 'in_progress' | 'completed' | 'pending' | 'waiting';
  updated_at?: string;
  url?: string;
}
