import type { TeamSimple } from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Groups of organization members that gives permissions on specified repositories.
 */
export interface Team {
  id: number;
  node_id: string;
  name: string;
  slug: string;
  description: string | null;
  privacy?: string;
  notification_setting?: string;
  permission: string;
  permissions?: {
    pull: boolean,
    triage: boolean,
    push: boolean,
    maintain: boolean,
    admin: boolean
  };
  url: string;
  html_url: string;
  members_url: string;
  repositories_url: string;
  parent: null | TeamSimple;
}
