/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describe whether all repositories have been selected or there's a selection involved
 */
export type WebhooksRepositorySelection = 'all' | 'selected';
