/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The [`git ref`](https://docs.github.com/rest/git/refs#get-a-reference) resource.
 */
export type WebhooksRef = string;
