/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The media type used to serialize the payloads. Supported values include `json` and `form`. The default is `form`.
 */
export type WebhookConfigContentType = string;
