/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The `pending_cancellation` and `pending_tier_change` event types will include the date the cancellation or tier change will take effect.
 */
export type WebhooksEffectiveDate = string;
