/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An array of repository objects that the installation can access.
 */
export type WebhooksRepositories = {
  full_name: string,
  /**
   * Unique identifier of the repository
   */
  id: number,
  /**
   * The name of the repository.
   */
  name: string,
  node_id: string,
  /**
   * Whether the repository is private or public.
   */
  private: boolean
}[];
