import type { CvssSeverities } from './index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The details of the security advisory, including summary, description, and severity.
 */
export interface WebhooksSecurityAdvisory {
  cvss: {
    score: number,
    vector_string: string | null
  };
  cvss_severities?: CvssSeverities;
  cwes: {
    cwe_id: string,
    name: string
  }[];
  description: string;
  ghsa_id: string;
  identifiers: {
    type: string,
    value: string
  }[];
  published_at: string;
  references: {
    url: string
  }[];
  severity: string;
  summary: string;
  updated_at: string;
  vulnerabilities: {
    first_patched_version: {
      identifier: string
    } | null,
    package: {
      ecosystem: string,
      name: string
    },
    severity: string,
    vulnerable_version_range: string
  }[];
  withdrawn_at: string | null;
}
