import type {
  EnterpriseWebhooks, OrganizationCustomProperty, OrganizationSimple, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CustomPropertyCreatedEvent {
  action: 'created';
  definition: OrganizationCustomProperty;
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  sender?: SimpleUser;
}
