import type {
  CustomPropertyValue, EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CustomPropertyValuesUpdatedEvent {
  action: 'updated';
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  repository: RepositoryWebhooks;
  organization: OrganizationSimple;
  sender?: SimpleUser;
  /**
   * The new custom property values for the repository.
   */
  new_property_values: CustomPropertyValue[];
  /**
   * The old custom property values for the repository.
   */
  old_property_values: CustomPropertyValue[];
}
