import type {
  EnterpriseWebhooks, FullRepository, OrganizationSimple, SecurityAndAnalysis, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SecurityAndAnalysisEvent {
  changes: {
    from?: {
      security_and_analysis?: SecurityAndAnalysis
    }
  };
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  repository: FullRepository;
  sender?: SimpleUser;
}
