import type {
  OrganizationSimple, ProjectsV2Project, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProjectsV2ClosedEvent {
  action: 'closed';
  installation?: SimpleInstallation;
  organization: OrganizationSimple;
  projects_v2: ProjectsV2Project;
  sender: SimpleUser;
}
