import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MetaDeletedEvent {
  action: 'deleted';
  enterprise?: EnterpriseWebhooks;
  /**
   * The modified webhook. This will contain different keys based on the type of webhook it is: repository, organization, business, app, or GitHub Marketplace.
   */
  hook: {
    active: boolean,
    config: {
      content_type: 'json' | 'form',
      insecure_ssl: string,
      secret?: string,
      url: string
    },
    created_at: string,
    events: (
      | '*'
      | 'branch_protection_rule'
      | 'check_run'
      | 'check_suite'
      | 'code_scanning_alert'
      | 'commit_comment'
      | 'create'
      | 'delete'
      | 'deployment'
      | 'deployment_status'
      | 'deploy_key'
      | 'discussion'
      | 'discussion_comment'
      | 'fork'
      | 'gollum'
      | 'issues'
      | 'issue_comment'
      | 'label'
      | 'member'
      | 'membership'
      | 'meta'
      | 'milestone'
      | 'organization'
      | 'org_block'
      | 'package'
      | 'page_build'
      | 'project'
      | 'project_card'
      | 'project_column'
      | 'public'
      | 'pull_request'
      | 'pull_request_review'
      | 'pull_request_review_comment'
      | 'pull_request_review_thread'
      | 'push'
      | 'registry_package'
      | 'release'
      | 'repository'
      | 'repository_import'
      | 'repository_vulnerability_alert'
      | 'secret_scanning_alert'
      | 'secret_scanning_alert_location'
      | 'security_and_analysis'
      | 'star'
      | 'status'
      | 'team'
      | 'team_add'
      | 'watch'
      | 'workflow_job'
      | 'workflow_run'
      | 'repository_dispatch'
      | 'projects_v2_item'
    )[],
    id: number,
    name: string,
    type: string,
    updated_at: string
  };
  /**
   * The id of the modified webhook.
   */
  hook_id: number;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  repository?: null | RepositoryWebhooks;
  sender?: SimpleUser;
}
