import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WorkflowDispatchEvent {
  enterprise?: EnterpriseWebhooks;
  inputs: {
    [k: string]: unknown | undefined
  } | null;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  ref: string;
  repository: RepositoryWebhooks;
  sender: SimpleUser;
  workflow: string;
}
