import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SecretScanningScanCompletedEvent {
  action: 'completed';
  /**
   * What type of scan was completed
   */
  type: 'backfill' | 'custom-pattern-backfill' | 'pattern-version-backfill';
  /**
   * What type of content was scanned
   */
  source: 'git' | 'issues' | 'pull-requests' | 'discussions' | 'wiki';
  /**
   * The time that the alert was resolved in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
   */
  started_at: string;
  /**
   * The time that the alert was resolved in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
   */
  completed_at: string;
  secret_types?: string[] | null;
  custom_pattern_name?: string | null;
  custom_pattern_scope?:
    | ('repository' | 'organization' | 'enterprise' | null)
    | null;
  repository?: RepositoryWebhooks;
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  organization?: OrganizationSimple;
  sender?: SimpleUser;
}
