import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser, WebhooksMarketplacePurchase, WebhooksPreviousMarketplacePurchase 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MarketplacePurchaseCancelledEvent {
  action: 'cancelled';
  effective_date: string;
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  marketplace_purchase: WebhooksMarketplacePurchase;
  organization?: OrganizationSimple;
  previous_marketplace_purchase?: WebhooksPreviousMarketplacePurchase;
  repository?: RepositoryWebhooks;
  sender: SimpleUser;
}
