import type {
  EnterpriseWebhooks, OrganizationSimple, RepositoryWebhooks, SimpleInstallation, SimpleUser, WebhooksMarketplacePurchase 
} from '../common/index.d.ts';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MarketplacePurchasePendingChangeEvent {
  action: 'pending_change';
  effective_date: string;
  enterprise?: EnterpriseWebhooks;
  installation?: SimpleInstallation;
  marketplace_purchase: WebhooksMarketplacePurchase;
  organization?: OrganizationSimple;
  previous_marketplace_purchase?: {
    account: {
      id: number,
      login: string,
      node_id: string,
      organization_billing_email: string | null,
      type: string
    },
    billing_cycle: string,
    free_trial_ends_on: string | null,
    next_billing_date?: string | null,
    on_free_trial: boolean,
    plan: {
      bullets: string[],
      description: string,
      has_free_trial: boolean,
      id: number,
      monthly_price_in_cents: number,
      name: string,
      price_model: 'FREE' | 'FLAT_RATE' | 'PER_UNIT',
      unit_name: string | null,
      yearly_price_in_cents: number
    },
    unit_count: number
  };
  repository?: RepositoryWebhooks;
  sender: SimpleUser;
}
